### ISSUE TITLE
Skype attach timeout

### ISSUE THREAD

**Issue by Somepony** [awahlig/skype4py#45]
Traceback (most recent call last):
  File "pony_bot.py", line 7, in <module>
    skype.Attach()
  File "C:\Python27\lib\site-packages\Skype4Py\skype.py", line 408, in Attach
    self._Api.attach(self.Timeout, Wait)
  File "C:\Python27\lib\site-packages\Skype4Py\api\windows.py", line 184, in attach
    raise SkypeAPIError('Skype attach timeout')
Skype4Py.errors.SkypeAPIError: Skype attach timeout

Another application (python.exe) is attempting to access Skype , but we are unable to respond. Please try to restart the application.

Python 32-bit, Windows 8.

**Comment by GreatDragonus** [comment]
Actually I have the same issue on Win8 (x64).
While everything works OK on Win7 systems.

I've done some tests and so far I can tell the next:
- python version is not the cause of the issue. Tested on 2.7.3, 2.7.4, 2.7.9 (x86 of course)
- skype version is not the cause. Tested on 6.20 and 7+

I have 3 racks. Two with Win7 x64 (with latest updates) on them and one with Win8 x64 (with almost no updates).

**Comment by dizzyupthegirl** [comment]
Was a resolution ever found for this issue?

**Comment by nikswap** [comment]
Hi. It can be due to MS removing the API, for its skype-bot api.

**Comment by zjjgit** [comment]
How to solve this problem?

**Comment by Cosmos19** [comment]
i am also facing this problem.
Python 2.7.13 (32bit)
Windows 7 64bit

**Comment by Sumontanaskar** [comment]
Hi friends,
I have found that previously i created multiple account from my PC and that time i was login from secondary account. When i logout from Secondary Skype account and login from primary then it works fine.
